name: elegant
description: Elegant Chat.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.2+20

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter_localizations:
      sdk: flutter
  page_view_indicators: ^1.3.1
  firebase_core: ^0.4.0+9
  firebase_auth: ^0.14.0+5
  emoji_picker: ^0.1.0
  image_crop: ^0.4.0
  cloud_firestore: ^0.12.9+5
  firebase_messaging: ^6.0.16
  flutter_svg: ^0.20.0-nullsafety.3
  image_picker: ^0.6.5
  firebase_storage: ^3.1.5
  progress_dialog: ^1.2.2
  provider: ^4.0.1
  url_launcher: ^3.0.1
  intl:
  cached_network_image: ^2.1.0+1
  uuid: 2.0.4
  video_thumbnail: ^0.2.1
  path_provider: 1.6.7
  photo_view: 0.9.2
  video_player: 0.10.9+1
  http: 0.12.1
  share: ^0.6.4+3
  country_list_pick: ^1.0.1+3
  select_form_field: ^1.1.0
  agora_rtc_engine: ^3.1.2
  permission_handler: ^5.0.1
  soundpool: ^1.0.1
  random_string: ^2.1.0
  auto_direction: ^0.0.5
  audioplayers:
  flutter_audio_recorder: ^0.5.5
  percent_indicator: ^2.1.9+1
  toast: ^0.1.5
  #emoji_chooser: ^0.9.2
  flutter_keyboard_visibility: ^3.2.2
  # password: ^1.0.0
#  encrypt: ^4.0.0
  shared_preferences: ^0.5.6+2
  flutter_colorpicker: ^0.2.3
  avatar_letter: ^1.0.1
  camera: ^0.5.8+5
  story_view: ^0.12.3
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/locale/
    - assets/sounds/
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto.ttf

    - family: sanFran
      fonts:
        - asset: fonts/SF-Pro-Display-Semibold.otf

    - family: alqabas
      fonts:
        - asset: assets/fonts/cair.ttf